mysite/accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name='accounts'

urlpatterns=[
   # url(r'^signup/$',views.signup_view,name='signup'),
    path('',views.signup_view,name="signup"),
    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout")
]

mysite/blog/urls.py
from . import views
from django.urls import path,include

#app_name='blog'

urlpatterns=[

    path('',views.PostList.as_view(),name='home'),
    path('<slug:slug>/',views.post_detail,name='post_detail'),
    path('upvote', views.upvote,name='upvote'),
    path('downvote', views.downvote,name='downvote'),
    path('reply',views.replytocomment,name='reply'),
    path('edit',views.editComment,name='edit'),
    path('save',views.save,name='save'),
    path('nArticle',views.nArticle,name='nArticle'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',include('accounts.urls')),
    #path('',include("django.contrib.auth.urls")),
    path('',include('blog.urls')),
]

mysite/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>The Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }

        .dark-mode {
            background-color: grey;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Poor mans blog</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!--<button>Helo</button>-->
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                            <li class="nav-item text-black">
                                  <button onClick ="myFunction()">Toggle Dark Mode</button>
                                </li>
                        <li class="nav-item text-black">
                            {% if user.is_authenticated%}
                            <form class="logout-link nav-link text-black font-weight-bold">
                                    <button type="submit">user:{{user.username}}</button>
                                </form>
                            {% else %}
                            <form class="logout-link nav-link text-black font-weight-bold" action="{% url 'accounts:signup' %}" method="GET">
                                    <button type="submit">Register</button>
                                </form>
                            {%endif%}
                        </li>
                        <li class="nav-item text-black">
                            {%if user.is_authenticated%}
                            <form class="logout-link nav-link text-black font-weight-bold" action="{% url 'accounts:logout' %}" method="POST">
                                {% csrf_token %}
                                <button type="submit">Logout</button>
                            </form>
                            {% else %}
                            <form class="logout-link nav-link text-black font-weight-bold" action="{% url 'accounts:login' %}" method="GET">
                                <button type="submit">Log in</button>
                            </form>
                            {%endif%}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->

        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; All the people I stole the code from</p>
        </footer>
        <script>
        function myFunction(){
            var element = document.body;
            var element2= document.getElementById("myClass");
            element.classList.toggle("dark-mode");
            element2.classList.toggle("dark-mode");
        }
        </script>
        </body>
    </body>
</html>

mysite/templates/edit.html
{% extends 'base.html' %} {% block content %}
<h1>Edit</h1>

{%if comment_id%}
<form method = 'POST' style="margin-top:1.3em" action="{%url 'save'%}">
    {% csrf_token %}
    <input type="submit text" name="text" value="{{commentText}}">
    <input type="hidden"  name="comment_id" value="{{comment_id}}">
    <button type="submit" class="btn btn-primary btn-lb">Save</button>

</form>
{%endif%}

{%if post_id%}
<form method = 'POST' style="margin-top:1.3em" action="{%url 'save'%}">
    {% csrf_token %}
    <input type="submit text" name="text" value="{{postText}}" width="200 px" height="40 px">
    <input type="hidden"  name="post_id" value="{{post_id}}">
    <button type="submit" class="btn btn-primary btn-lb">Save</button>

</form>
{%endif%}

{% endblock content %}

mysite/templates/index.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my budget Blog </h3>
                    <p class="text-light">I love Django as much as the next person
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":10" }}...</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                    {% if post.author|stringformat:"s" == user.username or user.username == "admin" %}
                        <form method="POST" action="{% url 'edit'%}" style="margin-top: 1.3em;">
                            {% csrf_token %}
                            <input type="hidden"  name="post_id" value="{{post.id}}">
                            <button type="submit" class="btn btn-primary  btn-lg">EDIT</button>
                        </form>
                    {%endif%}
                </div>
            </div>
            
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

mysite/templates/login.html
{%extends 'base.html'%}

{%block content%}
<h1>Log in</h1>
<iframe name="dummyframe" id="dummyframe" style="display: none;"></iframe>
<form class="site-form" action="{% url 'accounts:login'%}" method="POST">
    {%csrf_token%}
    {{form}}
    <input type="submit" value="Log in">
</form>
{%endblock%}

mysite/templates/nArticle.html
{% extends 'base.html' %} {% block content %}
<h1>Write new Article</h1>
<form method="post" action="{% url 'nArticle'  %}" style="margin-top: 1.3em">
        {% csrf_token %}
    <div style="padding : 10px">
        <a>New title</a>
        <a>{{ArticleForm.title}}</a>
    </div>

    <div style="padding : 10px">
            <a>Slug</a>
            <a>{{ArticleForm.slug}}</a>
    </div>


    <div style="padding : 10px">
        <a>Text</a>
        <a>{{ArticleForm.content}}</a>
    </div>
    
    <input class='small' type='submit' value="PUBLISH" name='publish'>
</form>

{% endblock content %}

mysite/templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}

    <div class="col-md-8 card mb-4  mt-3 "id = "myClass">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        {% if not comment.parent_id and comment.active%}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            <a>By {{ comment.name }}, Votes: {{comment.votes.count}}</a>
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {%if user.is_authenticated%}
            <form method="post" action="{% url 'reply'%}" style="margin-top: 1.3em;">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <input type="hidden"  name="comment_id" value="{{comment.id}}">
                <button type="submit" class="btn btn-primary  btn-lg">Reply</button>
            </form>
            
            {%if comment.name|stringformat:"s" == user.username or user.username == "admin" %}
              <!-- dodano test za edit-->
              <form method="POST" action="{% url 'edit'%}" style="margin-top: 1.3em;">
                {% csrf_token %}
                <input type="hidden"  name="comment_id" value="{{comment.id}}">
                <button type="submit" class="btn btn-primary  btn-lg">EDIT</button>
              </form>
            {%endif%}

            <form method="post" action="{% url 'upvote'  %}" style="margin-top: 1.3em">
              {% csrf_token %}
              <input class='small' type='submit' value='+1CHANGED' name='commentup'>
              <input type="hidden" name="comment_id" value="{{comment.id}}">
          </form>
          <form method="post" action="{% url 'downvote'  %}" style="margin-top: 1.3em">
            {% csrf_token %}
            <input class='small' type='submit' value='-1Changed'  name='commentdown'>
            <input type="hidden" name="comment_id" value="{{comment.id}}">
        </form>
            {%else%}
            <div class="card-body">
                <h3>Must be logged in to reply</h3>
            </div>
            {%endif%}
        {%endif%}


        <div class = "replied-comments container mt-2">
          {%for reply in comment.replies.all%}
          {%if reply.active%}
          <small>
          <div class="comments" style="padding: 10px;">
                <p class="font-weight-bold">
                    <a>By {{ reply.name }}, Votes: {{reply.votes.count}}</a>
                    <span class=" text-muted font-weight-normal">
                      {{ reply.created_on }}
                    </span>
                </p>
                {{ reply.body | linebreaks }}

                {% if user.is_authenticated%}
              <form method="post" action="{% url 'reply' %}" style="margin-top: 1.3em;">
                  {{ comment_form.as_p }}
                  {% csrf_token %}
                  <input type="hidden" name="comment_id" value="{{reply.id}}">
                  <button type="submit" class="btn btn-primary  btn-lg">ReplyChanged</button>
              </form>
              <!-- dodano test za edit-->
            {% if comment.name|stringformat:"s" == user.username or user.username == "admin" %}
              <form method="POST" action="{% url 'edit'%}" style="margin-top: 1.3em;">
                {% csrf_token %}
                <input type="hidden"  name="comment_id" value="{{comment.id}}">
                <button type="submit" class="btn btn-primary  btn-lg">EDIT</button>
              </form>
            {%endif%}

              <form method="post" action="{% url 'upvote'  %}" style="margin-top: 1.3em">
                  {% csrf_token %}
                  <input class='small' type='submit' value='+1CHANGED' name='commentup'>
                  <input type="hidden" name="comment_id" value="{{reply.id}}">
              </form>
              <form method="post" action="{% url 'downvote'  %}" style="margin-top: 1.3em">
                {% csrf_token %}
                <input class='small' type='submit' value='-1Changed'  name='commentdown'>
                <input type="hidden" name="comment_id" value="{{reply.id}}">
            </form>
              {%endif%}
            </div>
          </small>
          {%endif%}

          {%endfor%}
          <div class="form-group row">
            

          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {%if user.is_authenticated%}
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
    {%else%}
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <h3>Must be logged in to comment</h3>
      </div>
    </div>
    {%endif%}
  </div>
</div>
{% endblock content %}

mysite/templates/sidebar.html
        {% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
{%if user.is_authenticated%}
<div class="col-md-4 float-right ">
<div class="card my-4">
    
        <h5 class="card-header">For Writers</h5>
    <div class="card-body">
        
        <form method="GET" action="{%url 'nArticle'%}">
          <input class="btn btn-danger" type="submit" value = "New Article">
        </form>
    </div>
  
</div>
</div>
{%endif%}
{% endblock sidebar %}

mysite/templates/signup.html
{%extends 'base.html'%}

{%block content%}
<h1>Sign up</h1>
<iframe name="dummyframe" id="dummyframe" style="display: none;"></iframe>
<form class="site-form"  method="POST">
    {%csrf_token%}
    {{form}}
    <input type="submit" value="signup"action="{%url 'accounts:signup'%}" >
</form>
{%endblock%}